openapi: 3.0.0

servers:
- description: Local server
  url: http://localhost:3000/api/v0
info:
  $ref: './info/index.yaml'

tags:
  $ref: './tags/index.yaml'

paths:
  $ref: './paths/index.yaml'

components:
    $ref: './definitions/index.yaml'

security:
- ApiJWTAuth: []